/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author santi
 */
public class session extends javax.swing.JFrame {

    /**
     * Creates new form sesion
     */
    public session() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbcorr = new javax.swing.JLabel();
        txtcorr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbcon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnsal = new javax.swing.JButton();
        btning = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/katty perry.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setText("INICIO DE SESION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lbcorr.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbcorr.setText("CORREO:");
        jPanel1.add(lbcorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 10));

        txtcorr.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtcorr.setBorder(null);
        txtcorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorrActionPerformed(evt);
            }
        });
        jPanel1.add(txtcorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, 20));

        lbcon.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbcon.setText("CONTRASEÑA:");
        jPanel1.add(lbcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 280, 20));

        btnsal.setBackground(new java.awt.Color(58, 0, 83));
        btnsal.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnsal.setForeground(new java.awt.Color(255, 255, 255));
        btnsal.setText("SALIR");
        btnsal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalMouseExited(evt);
            }
        });
        jPanel1.add(btnsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 110, 30));

        btning.setBackground(new java.awt.Color(58, 0, 83));
        btning.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btning.setForeground(new java.awt.Color(255, 255, 255));
        btning.setText("INGRESAR");
        btning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btningMouseClicked(evt);
            }
        });
        jPanel1.add(btning, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 110, 30));

        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPRESA DE HOTELERIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 410, 40));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aaaaaaaaaaa.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 410, 100));

        Fondo.setBackground(new java.awt.Color(255, 0, 204));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/we are young.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 410, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtcorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorrActionPerformed

    private void btnsalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalMouseClicked
        // TODO add your handling code here:
     cliente Verformulario=new cliente();
        Verformulario.setVisible(true);
        
        
    }//GEN-LAST:event_btnsalMouseClicked

    private void btnsalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalMouseExited
        
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnsalMouseExited

    private void btningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btningMouseClicked
        cliente Verformulario=new cliente();
        Verformulario.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btningMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new session().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btning;
    private javax.swing.JButton btnsal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbcon;
    private javax.swing.JLabel lbcorr;
    private javax.swing.JTextField txtcorr;
    // End of variables declaration//GEN-END:variables
}
